### ISSUE TITLE
bug: schob object in array 

### ISSUE THREAD

**Issue by productdevbook** [huntersofbook/huntersofbook#121]
https://github.com/huntersofbook/huntersofbook/blob/29a836e9690b8c786ea89dddc55240447e016752/packages/schob/test/index.test.ts#L193

I can't pass 4 tests. I need help on this.

![image](https://user-images.githubusercontent.com/38668796/201873248-7be299fa-1e7b-4d85-af46-5447845b40e8.png)

**Comment by claranceliberi** [comment]
I'll take a look mate
