### ISSUE TITLE
Can't install @huntersofbook/plausible-nuxt with NPM

### ISSUE THREAD

**Issue by oezkancodes** [huntersofbook/huntersofbook#129]
Node v16.16.0

I tried installing `@huntersofbook/plausible-nuxt` with

```bash
npm i -D @huntersofbook/plausible-nuxt
```

or

```bash
npm add @huntersofbook/plausible-nuxt
```

but always receive the following error message:

```
npm ERR! code EUNSUPPORTEDPROTOCOL
npm ERR! Unsupported URL Type "workspace:": workspace:*
```

The installation of other NPM packages works without any problems.

**Comment by productdevbook** [comment]
I will send `@huntersofbook/plausible-nuxt` `v0.5.1` soon.
