### ISSUE TITLE
Headless component

### ISSUE THREAD

**Issue by jiblett1000** [huntersofbook/huntersofbook#144]
Hello,

Wondering if there are plans to make this a "headless" component. The only reason I'm looking to use this rather than the widget provided by Chatwoot is to be able to customize the style of the component(s). Being forced to use another ui library renders this module unusable (for me at least).

Thanks

**Comment by productdevbook** [comment]
Hi,

Can you send me some sample code? I want to examine. To do exactly what you're talking about.

**Comment by jiblett1000** [comment]
@productdevbook Thanks for the quick response! Something similar to https://headlessui.com/. So that the component state/logic is separated from the html/css. This would make it usable with any ui/css framework/etc.

**Comment by productdevbook** [comment]
Chatwoot ->

In my spare time, I will do research so that special designs can be made. But I don't know when it will end or I can do it. But I'll still try.

**Comment by jiblett1000** [comment]
@productdevbook I appreciate it. If I get the time, I will try to contribute as well.

**Comment by productdevbook** [comment]
This library has been moved. [Link](https://github.com/productdevbookcom/chatwoot)
