### ISSUE TITLE
NaiveUI: Global config with layouts

### ISSUE THREAD

**Issue by Teranode** [huntersofbook/huntersofbook#179]
Have you been able to make naive-ui wprl with layouts and the global config?

Something like:

app.vue:
```html
<template>
    <n-config-provider :cls-prefix="'app'" abstract :inline-theme-disabled="true">
        <n-global-style />
        <n-message-provider :placement="messagePlacement">
            <n-notification-provider>
                <n-dialog-provider>
                    <NuxtLayout>
                        <NuxtPage />
                    </NuxtLayout>
                </n-dialog-provider>
            </n-notification-provider>
        </n-message-provider>
    </n-config-provider>
</template>
```

layout/default.vue
```html
<template>
    <n-layout class="w-full h-screen" has-sider>
        <n-layout-sider>
        </n-layout-sider>
        <n-layout id="main-content"  class="n-layout n-layout--static-positioned" embedded>
            <n-layout-header class="n-layout-header n-layout-header--static-positioned" style="height: 54px;">
            </n-layout-header>
            <Simplebar class="w-full" data-simplebar="init" style="height: calc(100vh - 54px);">
                <slot />
            </Simplebar>
        </n-layout>
    </n-layout>
</template>
```

everything works completely fine in dev mode, but doing `yarn build` ends up with `document is not defined`. putting a `client-only` component over `n-config-global-provider` ends up making ssr for pages that use `useFetch` and other ssr related  functions moot since its turning all the components/pages into client side ones. 

I also tried change the mode of the component imports to 'client' but that also doesnt work as theyre giving off 'server-placeholder' errors.

**Comment by Teranode** [comment]
disabling inline theme will break ssr

**Comment by productdevbook** [comment]
stackblitz can you send me a demo i can play on ? and new version publish v0.6.0
