### ISSUE TITLE
Fails to load with the new Nuxt 3 version

### ISSUE THREAD

**Issue by raducretu** [huntersofbook/huntersofbook#191]
On Nuxt 3 version ^3.2.2, the module does not load and throws the following error:
`
sdk.js:1 Uncaught SyntaxError: Unexpected token '<'
`

**Comment by raducretu** [comment]
The new version still generated the error
<img width="950" alt="image" src="https://user-images.githubusercontent.com/85927/221688211-1c3862ac-4c4b-483b-b0bf-6d621b4e46a9.png">

**Comment by productdevbook** [comment]
Are you sure that this problem is from this lib, because the demos and all of it work where I use it. There seems to be something on the code on your side

**Comment by raducretu** [comment]
The same code works with any Nuxt prior to 3.2, so I guess from Nuxt 3.1 to 3.2 something probably changed for hooks, plugins, causing this … do you have a demo with Nuxt 3.2 and chatwoot?

**Comment by productdevbook** [comment]
https://github.com/huntersofbook/huntersofbook/tree/main/projects/chatwoot/packages/nuxt/playground

**Comment by productdevbook** [comment]
stackblitz demo create please

**Comment by raducretu** [comment]
https://stackblitz.com/edit/nuxt-starter-dnv6gn?file=nuxt.config.ts,package.json

Fresh Nuxt 3.2.3 install and chatwoot ... and same error

**Comment by raducretu** [comment]
any idea?

**Comment by productdevbook** [comment]
I'll try to do a review today, another person raised the same issue

**Comment by raducretu** [comment]
ok, thanks, but the stackblitz demo has the same error

**Comment by raducretu** [comment]
Thanks for digging into this

**Comment by wilDriven** [comment]
I'm using Nuxt 3.3.1 and getting a slightly different error but still not loading:

`Uncaught (in promise) Error: Chatwoot not loaded`

**Comment by productdevbook** [comment]
`@huntersofbook/chatwoot` Deprecate package.

New repo, fixed all problems.

https://github.com/productdevbookcom/chatwoot

Don't forget to support and give stars.
