### ISSUE TITLE
Fuoc when loading naive-ui playground

### ISSUE THREAD

**Issue by productdevbook** [huntersofbook/huntersofbook#196]
### Discussed in https://github.com/huntersofbook/huntersofbook/discussions/194

<div type='discussions-op-text'>

<sup>Originally posted by **marr** February 25, 2023</sup>
Hello, thanks for publishing out some of these great modules. I'm playing around with the naive-ui-nuxt module and noticing a fuoc (flash of unstyled content) when loading the page. I have tested with cache enabled in production mode and it still appears. Is that something that can be corrected?</div>

**Comment by productdevbook** [comment]
https://stackblitz.com/edit/github-jljeju?file=pages/index.vue

**Comment by productdevbook** [comment]
@marr [0.7.0](https://www.npmjs.com/package/@huntersofbook/naive-ui-nuxt/v/0.7.0)

check new version, and back please

**Comment by marr** [comment]
> @marr [0.7.0](https://www.npmjs.com/package/@huntersofbook/naive-ui-nuxt/v/0.7.0)
> 
> check new version, and back please

Thanks @productdevbook -- I still see the issue using 0.7.0

**Comment by productdevbook** [comment]
[0.7.1](https://www.npmjs.com/package/@huntersofbook/naive-ui-nuxt/v/0.7.1)

new version

re tested

**Comment by marr** [comment]
> [0.7.1](https://www.npmjs.com/package/@huntersofbook/naive-ui-nuxt/v/0.7.1)
> 
> new version
> 
> re test

looks good
