### ISSUE TITLE
Uncaught SyntaxError: ambiguous indirect export: darkTheme

### ISSUE THREAD

**Issue by durbanitas** [huntersofbook/huntersofbook#35]
Got an `500 error: Uncaught SyntaxError: ambiguous indirect export: darkTheme`

![theme-error](https://user-images.githubusercontent.com/34290127/190858214-a7ceaba1-297c-4e01-b155-e375cc972103.png)

## Code (index.vue)

```js
<script setup>
import { NConfigProvider, darkTheme, NGlobalStyle } from 'naive-ui'
const theme = $ref(darkTheme)
</script>

<template>
  <div>
    <NConfigProvider :theme="theme">
      <NGlobalStyle />
      <div>
        Nuxt module playground!
        <NButton>Default</NButton>
      </div>
    </NConfigProvider>
  </div>
</template>
```

**Comment by productdevbook** [comment]
Please only add. Because all auto import. 

```
<script setup lang="ts">
  
</script>

<template>
  <NConfigProvider :theme="darkTheme">
    <NGlobalStyle />
    <div>
      Nuxt module playground!
      <NButton>Default</NButton>
    </div>
  </NConfigProvider>
</template>
```

**Comment by durbanitas** [comment]
Thanks for the quick response. In my current project I get the same error with your provided code.

I just created a new nuxt 3 app and added your module: now it works and I have no errors. I will try to migrate my project now the new plain template. Thx!
